package com.lys.zhku.model;

public class Authorities {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authorities.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authorities.authority
	 * @mbg.generated
	 */
	private String authority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authorities.enable
	 * @mbg.generated
	 */
	private Boolean enable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column authorities.remark
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authorities.id
	 * @return  the value of authorities.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authorities.id
	 * @param id  the value for authorities.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authorities.authority
	 * @return  the value of authorities.authority
	 * @mbg.generated
	 */
	public String getAuthority() {
		return authority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authorities.authority
	 * @param authority  the value for authorities.authority
	 * @mbg.generated
	 */
	public void setAuthority(String authority) {
		this.authority = authority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authorities.enable
	 * @return  the value of authorities.enable
	 * @mbg.generated
	 */
	public Boolean getEnable() {
		return enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authorities.enable
	 * @param enable  the value for authorities.enable
	 * @mbg.generated
	 */
	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column authorities.remark
	 * @return  the value of authorities.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column authorities.remark
	 * @param remark  the value for authorities.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}