package com.lys.zhku.model;

public class GroupAuthorities {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_authorities.group_id
     *
     * @mbg.generated
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_authorities.authority
     *
     * @mbg.generated
     */
    private String authority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_authorities.group_id
     *
     * @return the value of group_authorities.group_id
     *
     * @mbg.generated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_authorities.group_id
     *
     * @param groupId the value for group_authorities.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_authorities.authority
     *
     * @return the value of group_authorities.authority
     *
     * @mbg.generated
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_authorities.authority
     *
     * @param authority the value for group_authorities.authority
     *
     * @mbg.generated
     */
    public void setAuthority(String authority) {
        this.authority = authority;
    }
}