package com.lys.zhku.model;

public class RolesAuthorities {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles_authorities.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles_authorities.roles_id
	 * @mbg.generated
	 */
	private Integer rolesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles_authorities.authorities_id
	 * @mbg.generated
	 */
	private Integer authoritiesId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles_authorities.id
	 * @return  the value of roles_authorities.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles_authorities.id
	 * @param id  the value for roles_authorities.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles_authorities.roles_id
	 * @return  the value of roles_authorities.roles_id
	 * @mbg.generated
	 */
	public Integer getRolesId() {
		return rolesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles_authorities.roles_id
	 * @param rolesId  the value for roles_authorities.roles_id
	 * @mbg.generated
	 */
	public void setRolesId(Integer rolesId) {
		this.rolesId = rolesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles_authorities.authorities_id
	 * @return  the value of roles_authorities.authorities_id
	 * @mbg.generated
	 */
	public Integer getAuthoritiesId() {
		return authoritiesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles_authorities.authorities_id
	 * @param authoritiesId  the value for roles_authorities.authorities_id
	 * @mbg.generated
	 */
	public void setAuthoritiesId(Integer authoritiesId) {
		this.authoritiesId = authoritiesId;
	}
}