package com.lys.zhku.model;

public class Roles {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.role
	 * @mbg.generated
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.enable
	 * @mbg.generated
	 */
	private Boolean enable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.remark
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.id
	 * @return  the value of roles.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.id
	 * @param id  the value for roles.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.role
	 * @return  the value of roles.role
	 * @mbg.generated
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.role
	 * @param role  the value for roles.role
	 * @mbg.generated
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.enable
	 * @return  the value of roles.enable
	 * @mbg.generated
	 */
	public Boolean getEnable() {
		return enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.enable
	 * @param enable  the value for roles.enable
	 * @mbg.generated
	 */
	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.remark
	 * @return  the value of roles.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.remark
	 * @param remark  the value for roles.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}