package com.lys.zhku.model;

public class Students {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column students.users_username
	 * @mbg.generated
	 */
	private String usersUsername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column students.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column students.gender
	 * @mbg.generated
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column students.campus
	 * @mbg.generated
	 */
	private String campus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column students.department
	 * @mbg.generated
	 */
	private String department;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column students.major
	 * @mbg.generated
	 */
	private String major;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column students.grade
	 * @mbg.generated
	 */
	private Integer grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column students.classnum
	 * @mbg.generated
	 */
	private Integer classnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column students.dormitory
	 * @mbg.generated
	 */
	private String dormitory;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column students.users_username
	 * @return  the value of students.users_username
	 * @mbg.generated
	 */
	public String getUsersUsername() {
		return usersUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column students.users_username
	 * @param usersUsername  the value for students.users_username
	 * @mbg.generated
	 */
	public void setUsersUsername(String usersUsername) {
		this.usersUsername = usersUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column students.name
	 * @return  the value of students.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column students.name
	 * @param name  the value for students.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column students.gender
	 * @return  the value of students.gender
	 * @mbg.generated
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column students.gender
	 * @param gender  the value for students.gender
	 * @mbg.generated
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column students.campus
	 * @return  the value of students.campus
	 * @mbg.generated
	 */
	public String getCampus() {
		return campus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column students.campus
	 * @param campus  the value for students.campus
	 * @mbg.generated
	 */
	public void setCampus(String campus) {
		this.campus = campus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column students.department
	 * @return  the value of students.department
	 * @mbg.generated
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column students.department
	 * @param department  the value for students.department
	 * @mbg.generated
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column students.major
	 * @return  the value of students.major
	 * @mbg.generated
	 */
	public String getMajor() {
		return major;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column students.major
	 * @param major  the value for students.major
	 * @mbg.generated
	 */
	public void setMajor(String major) {
		this.major = major;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column students.grade
	 * @return  the value of students.grade
	 * @mbg.generated
	 */
	public Integer getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column students.grade
	 * @param grade  the value for students.grade
	 * @mbg.generated
	 */
	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column students.classnum
	 * @return  the value of students.classnum
	 * @mbg.generated
	 */
	public Integer getClassnum() {
		return classnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column students.classnum
	 * @param classnum  the value for students.classnum
	 * @mbg.generated
	 */
	public void setClassnum(Integer classnum) {
		this.classnum = classnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column students.dormitory
	 * @return  the value of students.dormitory
	 * @mbg.generated
	 */
	public String getDormitory() {
		return dormitory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column students.dormitory
	 * @param dormitory  the value for students.dormitory
	 * @mbg.generated
	 */
	public void setDormitory(String dormitory) {
		this.dormitory = dormitory;
	}


    
}