package com.lys.zhku.model;

public class UsersRoles {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_roles.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_roles.users_username
	 * @mbg.generated
	 */
	private String usersUsername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users_roles.roles_id
	 * @mbg.generated
	 */
	private Integer rolesId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_roles.id
	 * @return  the value of users_roles.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_roles.id
	 * @param id  the value for users_roles.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_roles.users_username
	 * @return  the value of users_roles.users_username
	 * @mbg.generated
	 */
	public String getUsersUsername() {
		return usersUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_roles.users_username
	 * @param usersUsername  the value for users_roles.users_username
	 * @mbg.generated
	 */
	public void setUsersUsername(String usersUsername) {
		this.usersUsername = usersUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users_roles.roles_id
	 * @return  the value of users_roles.roles_id
	 * @mbg.generated
	 */
	public Integer getRolesId() {
		return rolesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users_roles.roles_id
	 * @param rolesId  the value for users_roles.roles_id
	 * @mbg.generated
	 */
	public void setRolesId(Integer rolesId) {
		this.rolesId = rolesId;
	}
}