package com.lys.zhku.model;

import java.io.Serializable;

public class Userdetails implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1174851628162314388L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userdetails.users_username
	 * @mbg.generated
	 */
	private String usersUsername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userdetails.idcard
	 * @mbg.generated
	 */
	private String idcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userdetails.phonenum
	 * @mbg.generated
	 */
	private String phonenum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userdetails.shortnum
	 * @mbg.generated
	 */
	private String shortnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userdetails.email
	 * @mbg.generated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userdetails.qq
	 * @mbg.generated
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userdetails.urgentnum
	 * @mbg.generated
	 */
	private String urgentnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userdetails.birthplace
	 * @mbg.generated
	 */
	private String birthplace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userdetails.address
	 * @mbg.generated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userdetails.political
	 * @mbg.generated
	 */
	private String political;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userdetails.nation
	 * @mbg.generated
	 */
	private String nation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userdetails.remark
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userdetails.users_username
	 * @return  the value of userdetails.users_username
	 * @mbg.generated
	 */
	public String getUsersUsername() {
		return usersUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userdetails.users_username
	 * @param usersUsername  the value for userdetails.users_username
	 * @mbg.generated
	 */
	public void setUsersUsername(String usersUsername) {
		this.usersUsername = usersUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userdetails.idcard
	 * @return  the value of userdetails.idcard
	 * @mbg.generated
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userdetails.idcard
	 * @param idcard  the value for userdetails.idcard
	 * @mbg.generated
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userdetails.phonenum
	 * @return  the value of userdetails.phonenum
	 * @mbg.generated
	 */
	public String getPhonenum() {
		return phonenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userdetails.phonenum
	 * @param phonenum  the value for userdetails.phonenum
	 * @mbg.generated
	 */
	public void setPhonenum(String phonenum) {
		this.phonenum = phonenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userdetails.shortnum
	 * @return  the value of userdetails.shortnum
	 * @mbg.generated
	 */
	public String getShortnum() {
		return shortnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userdetails.shortnum
	 * @param shortnum  the value for userdetails.shortnum
	 * @mbg.generated
	 */
	public void setShortnum(String shortnum) {
		this.shortnum = shortnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userdetails.email
	 * @return  the value of userdetails.email
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userdetails.email
	 * @param email  the value for userdetails.email
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userdetails.qq
	 * @return  the value of userdetails.qq
	 * @mbg.generated
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userdetails.qq
	 * @param qq  the value for userdetails.qq
	 * @mbg.generated
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userdetails.urgentnum
	 * @return  the value of userdetails.urgentnum
	 * @mbg.generated
	 */
	public String getUrgentnum() {
		return urgentnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userdetails.urgentnum
	 * @param urgentnum  the value for userdetails.urgentnum
	 * @mbg.generated
	 */
	public void setUrgentnum(String urgentnum) {
		this.urgentnum = urgentnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userdetails.birthplace
	 * @return  the value of userdetails.birthplace
	 * @mbg.generated
	 */
	public String getBirthplace() {
		return birthplace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userdetails.birthplace
	 * @param birthplace  the value for userdetails.birthplace
	 * @mbg.generated
	 */
	public void setBirthplace(String birthplace) {
		this.birthplace = birthplace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userdetails.address
	 * @return  the value of userdetails.address
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userdetails.address
	 * @param address  the value for userdetails.address
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userdetails.political
	 * @return  the value of userdetails.political
	 * @mbg.generated
	 */
	public String getPolitical() {
		return political;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userdetails.political
	 * @param political  the value for userdetails.political
	 * @mbg.generated
	 */
	public void setPolitical(String political) {
		this.political = political;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userdetails.nation
	 * @return  the value of userdetails.nation
	 * @mbg.generated
	 */
	public String getNation() {
		return nation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userdetails.nation
	 * @param nation  the value for userdetails.nation
	 * @mbg.generated
	 */
	public void setNation(String nation) {
		this.nation = nation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userdetails.remark
	 * @return  the value of userdetails.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userdetails.remark
	 * @param remark  the value for userdetails.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}