package com.lys.zhku.model;

public class Workers {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workers.users_username
	 * @mbg.generated
	 */
	private String usersUsername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workers.position
	 * @mbg.generated
	 */
	private String position;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workers.users_username
	 * @return  the value of workers.users_username
	 * @mbg.generated
	 */
	public String getUsersUsername() {
		return usersUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workers.users_username
	 * @param usersUsername  the value for workers.users_username
	 * @mbg.generated
	 */
	public void setUsersUsername(String usersUsername) {
		this.usersUsername = usersUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workers.position
	 * @return  the value of workers.position
	 * @mbg.generated
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workers.position
	 * @param position  the value for workers.position
	 * @mbg.generated
	 */
	public void setPosition(String position) {
		this.position = position;
	}
}