package com.lys.zhku.model;

import com.lys.zhku.anno.NameMapping;

@NameMapping("工作人员信息")
public class Workers {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workers.users_username
	 * @mbg.generated
	 */
	@NameMapping("账号")
	private String usersUsername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workers.name
	 * @mbg.generated
	 */
	@NameMapping("姓名")
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workers.gender
	 * @mbg.generated
	 */
	@NameMapping("性别")
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column workers.position
	 * @mbg.generated
	 */
	@NameMapping("职位")
	private String position;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workers.users_username
	 * @return  the value of workers.users_username
	 * @mbg.generated
	 */
	public String getUsersUsername() {
		return usersUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workers.users_username
	 * @param usersUsername  the value for workers.users_username
	 * @mbg.generated
	 */
	public void setUsersUsername(String usersUsername) {
		this.usersUsername = usersUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workers.name
	 * @return  the value of workers.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workers.name
	 * @param name  the value for workers.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workers.gender
	 * @return  the value of workers.gender
	 * @mbg.generated
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workers.gender
	 * @param gender  the value for workers.gender
	 * @mbg.generated
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column workers.position
	 * @return  the value of workers.position
	 * @mbg.generated
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column workers.position
	 * @param position  the value for workers.position
	 * @mbg.generated
	 */
	public void setPosition(String position) {
		this.position = position;
	}
}