package com.lys.zhku.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lys.zhku.model.ClassroomSchedule;
import com.lys.zhku.pojo.web.Pagination;

public interface ClassroomScheduleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classroom_schedule
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classroom_schedule
	 * @mbg.generated
	 */
	int insert(ClassroomSchedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classroom_schedule
	 * @mbg.generated
	 */
	ClassroomSchedule selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classroom_schedule
	 * @mbg.generated
	 */
	List<ClassroomSchedule> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classroom_schedule
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ClassroomSchedule record);

	/**
	 * 根据分页参数获取分页记录总数
	 * @param pagination
	 * @return
	 */
	int selectCountByPagination(Pagination pagination);

	/**
	 * 根据分页参数获取分页记录
	 * @param pagination
	 * @return
	 */
	List<ClassroomSchedule> selectByPagination(Pagination pagination);

	/**
	 * 根据主键数组删除对应记录
	 * @param ids
	 * @return
	 */
	int deleteByPrimaryKeys(@Param("ids") Integer[] ids);	
}