package com.lys.zhku.mapper;

import com.lys.zhku.model.Classroom;
import com.lys.zhku.pojo.web.Pagination;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ClassroomMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classroom
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classroom
	 * @mbg.generated
	 */
	int insert(Classroom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classroom
	 * @mbg.generated
	 */
	Classroom selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classroom
	 * @mbg.generated
	 */
	List<Classroom> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classroom
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Classroom record);

	/**
	 * 根据分页参数获取分页记录总数
	 * @param pagination
	 * @return
	 */
	int selectCountByPagination(Pagination pagination);

	/**
	 * 根据分页参数获取分页记录
	 * @param pagination
	 * @return
	 */
	List<Classroom> selectByPagination(Pagination pagination);

	/**
	 * 根据主键数组删除对应记录
	 * @param ids
	 * @return
	 */
	int deleteByPrimaryKeys(@Param("ids") Integer[] ids);
}