package com.lys.zhku.mapper;

import com.lys.zhku.model.Datadict;
import com.lys.zhku.pojo.web.Pagination;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DatadictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datadict
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datadict
     *
     * @mbg.generated
     */
    int insert(Datadict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datadict
     *
     * @mbg.generated
     */
    Datadict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datadict
     *
     * @mbg.generated
     */
    List<Datadict> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datadict
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Datadict record);

	/**
	 * 根据enable的值获取其总记录数值
	 * @param enable
	 * @return
	 */
	int selectCountByEnable(Pagination pagination);

	/**
	 * 获取分页记录
	 * @param pagination
	 * @return
	 */
	List<Datadict> selectByPagination(Pagination pagination);

	int deleteByPrimaryKeys(@Param("ids") Integer[] ids);

	/**
	 * 根据Datadict的字段来查询列表
	 * @param datadict
	 * @return
	 */
	List<Datadict> getListByDatadict(Datadict datadict);
}