package com.lys.zhku.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lys.zhku.mapper.base.BaseMapper;
import com.lys.zhku.model.Dormitory;
import com.lys.zhku.pojo.web.Pagination;

public interface DormitoryMapper extends BaseMapper<Dormitory>{
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dormitory
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dormitory
	 * @mbg.generated
	 */
	int insert(Dormitory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dormitory
	 * @mbg.generated
	 */
	Dormitory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dormitory
	 * @mbg.generated
	 */
	List<Dormitory> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dormitory
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Dormitory record);

	/**
	 * 根据分页参数查找总记录数
	 * @param pagination
	 * @return
	 */
	int selectCountByPagination(Pagination pagination);

	/**
	 * 根据分页参数查找记录
	 * @param pagination
	 * @return
	 */
	List<Dormitory> selectByPagination(Pagination pagination);

	/**
	 * 根据主键数组删除记录
	 * @param ids
	 * @return
	 */
	int deleteByPrimaryKeys(@Param("ids") Integer[] ids);

}