package com.lys.zhku.mapper;

import com.lys.zhku.model.GroupMembers;
import java.util.List;

public interface GroupMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    int insert(GroupMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    GroupMembers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    List<GroupMembers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupMembers record);
}