package com.lys.zhku.mapper;

import com.lys.zhku.model.GroupAuthorities;
import java.util.List;

public interface GroupAuthoritiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authorities
     *
     * @mbg.generated
     */
    int insert(GroupAuthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_authorities
     *
     * @mbg.generated
     */
    List<GroupAuthorities> selectAll();
}