package com.lys.zhku.mapper;

import com.lys.zhku.mapper.base.BaseMapper;
import com.lys.zhku.model.Park;
import java.util.List;

public interface ParkMapper<T> extends BaseMapper<T>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbg.generated
     */
    int insert(Park record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbg.generated
     */
    Park selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbg.generated
     */
    List<Park> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Park record);
}