package com.lys.zhku.mapper;

import com.lys.zhku.model.RolesAuthorities;
import java.util.List;

public interface RolesAuthoritiesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_authorities
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_authorities
	 * @mbg.generated
	 */
	int insert(RolesAuthorities record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_authorities
	 * @mbg.generated
	 */
	RolesAuthorities selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_authorities
	 * @mbg.generated
	 */
	List<RolesAuthorities> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_authorities
	 * @mbg.generated
	 */
	int updateByPrimaryKey(RolesAuthorities record);
}