package com.lys.zhku.mapper;

import java.util.List;

import com.lys.zhku.model.Roles;
import com.lys.zhku.model.UsersRoles;

public interface RolesMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbg.generated
	 */
	int insert(Roles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbg.generated
	 */
	Roles selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbg.generated
	 */
	List<Roles> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Roles record);

	List<Roles> selectByUsersRolesList(List<UsersRoles> usersRolesList);

	Roles selectByRole(String role);
}