package com.lys.zhku.mapper;

import com.lys.zhku.model.Students;
import java.util.List;

public interface StudentsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table students
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String usersUsername);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table students
	 * @mbg.generated
	 */
	int insert(Students record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table students
	 * @mbg.generated
	 */
	Students selectByPrimaryKey(String usersUsername);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table students
	 * @mbg.generated
	 */
	List<Students> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table students
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Students record);
}