package com.lys.zhku.mapper;

import com.lys.zhku.model.Userdetails;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserdetailsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userdetails
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String usersUsername);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userdetails
	 * @mbg.generated
	 */
	int insert(Userdetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userdetails
	 * @mbg.generated
	 */
	Userdetails selectByPrimaryKey(String usersUsername);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userdetails
	 * @mbg.generated
	 */
	List<Userdetails> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userdetails
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Userdetails record);

	/**
	 * 根据usersUsernames(外键)数组删除记录,内存上永久删除
	 * @param usersUsernames
	 * @return
	 */
	int deleteByUsernames(@Param("usersUsernames") String[] usersUsernames);
}