package com.lys.zhku.mapper;

import com.lys.zhku.model.UsersRoles;
import java.util.List;

public interface UsersRolesMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_roles
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_roles
	 * @mbg.generated
	 */
	int insert(UsersRoles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_roles
	 * @mbg.generated
	 */
	UsersRoles selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_roles
	 * @mbg.generated
	 */
	List<UsersRoles> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_roles
	 * @mbg.generated
	 */
	int updateByPrimaryKey(UsersRoles record);

	/**
     * 根据users(id)查找记录
     * @param usersUsername
     * @return
     */
    List<UsersRoles> selectByUsersUsername(String usersUsername);
}