package com.lys.zhku.mapper;

import com.lys.zhku.model.Workers;
import com.lys.zhku.pojo.web.Pagination;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface WorkersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workers
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String usersUsername);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workers
	 * @mbg.generated
	 */
	int insert(Workers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workers
	 * @mbg.generated
	 */
	Workers selectByPrimaryKey(String usersUsername);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workers
	 * @mbg.generated
	 */
	List<Workers> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table workers
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Workers record);

	int selectTotalForPagination(Pagination pagination);

	List<Workers> selectForPagination(Pagination pagination);

	/**
	 * 根据userUsername数组删除对应的记录
	 * @param usersUsernames
	 * @return
	 */
	int deleteByUsernames(@Param("usersUsernames") String[] usersUsernames);
}